version: '3'

services:
  master:
    build: ..
    command: master
    tty: true
    ports:
      - "60000"
    volumes:
      - "./test/:/jmeter/test/"
    networks:
      - jmeter-network
  server:
    image: local_master
    command: server
    tty: true
    ports:
      - "50000"
      - "1099"
    volumes:
      - "./data_test/:/jmeter/data_test/"
    networks:
      - jmeter-network
    depends_on:
      - master

networks:
  jmeter-network:
